site_name: TimelyGator Docs
site_url: https://timelygator.github.io/timelygator/
repo_url: https://github.com/timelygator/timelygator/
repo_name: TimelyGator/TimelyGator
docs_dir: files
nav:
  - index.md
  - Frontend Design: frontend.md
  - Backend Architecture Design: 
    - Overview: backend.md
    - Database: database.md
    - Observers:
      - Window Observer: observers/window-observer.md
      - AFK Observer: observers/afk-observer.md
  - Sprint Docs:
    - Sprint 1: sprint/Sprint1.md
    - Sprint 2: sprint/Sprint2.md
    - Sprint 3: sprint/Sprint3.md
    - Sprint 4: sprint/Sprint4.md
  - API Reference: api.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.top
    - navigation.footer
    - navigation.expand
    - toc.follow
markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/mkdocsoad.css
plugins:
  - search
  - neoteroi.mkdocsoad